### ISSUE TITLE
Suggest to support Fitten

### ISSUE THREAD

**Issue by bon-ami** [Shougo/ddc-source-codeium#2]
I'm trying to use [Fitten](https://github.com/luozhiya/fittencode.nvim) which is similar to Codeium.
It would definitely be great if it runs with ddc. But I do not know lua and can only figure out [triggering_completion](https://github.com/luozhiya/fittencode.nvim/blob/b0bb77fbf605e747d8e72f7fcc3a337fafc6327f/lua/fittencode/engines/inline/init.lua#L154) is like `codeium#Complete`. Can we use `extmark_ids` for the results?
Thank you a lot.

**Comment by Shougo** [comment]
sorry.  I cannot support it.

This is just codeium completion source.
It does not support another AI API.

**Comment by Shougo** [comment]
```lua
function M:generate_one_stage(api_key, params, on_success, on_error)
  local url = URL.GENERATE_ONE_STAGE .. api_key .. '?ide=neovim&v=0.1.0'
  local data = params

  Promise:new(function(resolve, _)
    self.rest:post(url, {
      'Content-Type: application/json',
    }, data, function(response)
      resolve(response)
    end, function()
      schedule(on_error)
    end)
  end):forward(function(response)
    local generated_text = Resopnse._on_stage_response(response)
    if generated_text == nil then
      schedule(on_error)
    else
      schedule(on_success, generated_text)
    end
  end)
end
```

to access the REST API is better.
Because ddc is TypeScript.
